# ===========================
# FONT
# ===========================
[font]
size = 13.0

[font.normal]
family = "Cascadia Mono NF"
style  = "Regular"

[font.bold]
family = "Cascadia Mono NF"
style  = "Bold"

[font.italic]
family = "Cascadia Mono NF"
style  = "Italic"

# Colors (Everforest Dark)
# Default colors
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# # ===========================
# # COLORS (OneDark)
# # ===========================
# [colors.primary]
# background = "#1E2127"
# foreground = "#ABB2BF"

# [colors.cursor]
# cursor = "#AAAAAA"
# text = "#1E2127"

# [colors.selection]
# background = "#FFFFFF"

# [colors.normal]
# black = "#1E2127"
# red = "#E06C75"
# green = "#98C379"
# yellow = "#D19A66"
# blue = "#61AFEF"
# magenta = "#C678DD"
# cyan = "#56B6C2"
# white = "#ABB2BF"

# [colors.bright]
# black = "#5C6370"
# red = "#E06C75"
# green = "#98C379"
# yellow = "#D19A66"
# blue = "#61AFEF"
# magenta = "#C678DD"
# cyan = "#56B6C2"
# white = "#FFFFFF"

# ===========================
# WINDOW
# ===========================
[window]
opacity = 1.0
dynamic_title = true

[window.dimensions]
columns = 120
lines = 32

[window.padding]
x = 4
y = 4


# ===========================
# SCROLL
# ===========================
[scrolling]
history = 10000
multiplier = 3


# ===========================
# CURSOR
# ===========================
[cursor.style]
shape = "Block"
blinking = "On"


# ===========================
# SHELL
# ===========================
[terminal.shell]
program = "C:\\Program Files\\Git\\bin\\bash.exe"
# args = ["-NoLogo"]


# ===========================
# KEYBINDINGS
# ===========================
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Control"
action = "SpawnNewInstance"

# Ctrl+Shift+C sebagai interrupt
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"

# Ctrl+D untuk EOF
[[keyboard.bindings]]
key = "D"
mods = "Control"
chars = "\u0004"

[terminal]
